Import('env')
env = env.Clone()

env.ParseConfig('xml2-config --cflags --libs')
env.Append(LIBS = 'm')

Import('verObj')
env.Append(CPPPATH = '../auto')
env.Append(LINKFLAGS = verObj[0].get_internal_path())

env.Append(CPPPATH = '../common/inc')

env.Append(LIBS = 'netmirage-common')
env.Append(LIBPATH = '../common')

Import('targetSuffix')
app = env.Program('#bin/netmirage-core'+targetSuffix, Glob('*.c'))
env.Requires(app, verObj)

Default(app)