#pragma once

#include <stdint.h>

// The implementation of these functions is generated by scons

const char* getVersion(void);
uint16_t getVersionMajor(void);
uint16_t getVersionMinor(void);
uint16_t getVersionRevision(void);
