#pragma once

#include <stdint.h>

// The implementation of these functions is generated by scons

const char* getVersionString();
const uint16_t getVersionMajor();
const uint16_t getVersionMinor();
const uint16_t getVersionRevision();
