Import('env')

env.ParseConfig('xml2-config --cflags --libs')
env.ParseConfig('pkg-config --cflags --libs libcap')
env.Append(LIBS = 'm')

verObj = env.Object('../auto/version.c')
env.Append(LINKFLAGS = str(verObj[0]))

env.Append(CPPPATH = '../auto')
env.Append(CPPPATH = '../common')
env.Append(CPPPATH = '.')

env.Append(LIBS = 'netmirage-common')
env.Append(LIBPATH = '../common')

Import('targetSuffix')
app = env.Program("#bin/netmirage"+targetSuffix, Glob('*.c') + Glob('../common/*.c'))
env.Requires(app, verObj)
